### PR TITLE
Added more links to README.md

### PR DESCRIPTION
**Pull request by ghost**
Added resources for 
Intro to cybersecurity
Python 101
Python 201

### CODE REVIEW

**Comment by ghost** [comment]
requesting @emtuls  / @bikashdaga for merge

**Comment by emtuls** [comment]
Not going to add these as they are clearly just self promoting links and also resources that require payment or registration.
Can't verify the quality.

**Comment by ghost** [comment]
With due respect, PLEASE add a contribution guideline to this project. 
yes 2 of the above are free and 1 (Python 201) did required a One time payment of about 5-6 $
Again since no clear contribution guidelines exist, the pull was inevitable. 
Secondly I would like to work on improving the HTML version, honestly right now it seems to "not great" but to do so, there seems to be a deployment set, configuration of which is not visible. 
Kindly guide on how that can be arranged. 

Also, just because I posted them doesn't automatically mean they are not good, they are good , that I guarantee, would have appreciated if you actually went through them and judged them on quality and not "who's posting?"
never thought GitHub would behave like this.

**Comment by ghost** [comment]
@emtuls  please let know on the contrib guidelines if possible. No pressure!

**Pull request closed without merging**
